server:
  port: 80

spring:
  application:
    name: cloud-consumer-orde
  devtools:
    add-properties: false

eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://peer1:9000/eureka/, http://peer2:9002/eureka/,http://peer3:9003/eureka/