server:
  port: 9528

spring:
  application:
    name: cloud-getway-dynamic-routing
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_route #路由的id,没有固定规则要求唯一,建议配合服务器命名
#          uri: http://localhost:8901 #匹配后提供服务的路由地址
          uri: lb://CLOUD-HYSTRIX-OPENFEIGN-ORDER
          predicates:
            - Path=/payment/timeout/** #断言,路由相匹配的进行路由
        - id: payment_route2
#          uri: http://localhost:8901
          uri: lb://CLOUD-HYSTRIX-OPENFEIGN-ORDER
          predicates:
            - Path=/payment/ok/**

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9004/eureka
    fetch-registry: true
    register-with-eureka: true
