server:
  port: 8402

spring:
  application:
    name: cloud-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口,加入被占用会自动从8719开始+1,直接找到未被占用的端口
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: "*"