server:
  port: 8081

spring:
  application:
    name: cloud-provider-payment-service
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/tree-sys?characterEncoding=utf8&serverTimezone=UTC
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  profiles: provider-payment01
  devtools:
    add-properties: false

mybatis:
  mapper-locations: classpath*:/mappers/*.xml
  configuration:
    #  开启驼峰设置,还可以有其他设置比如别名等
    map-underscore-to-camel-case: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://peer1:9000/eureka/, http://peer2:9002/eureka/,http://peer3:9003/eureka/
---

server:
  port: 8082

spring:
  application:
    name: cloud-provider-payment-service
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/tree-sys?characterEncoding=utf8&serverTimezone=UTC
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  profiles: provider-payment02
  devtools:
    add-properties: false

mybatis:
  mapper-locations: classpath*:/mappers/*.xml
  configuration:
    #  开启驼峰设置,还可以有其他设置比如别名等
    map-underscore-to-camel-case: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://peer1:9000/eureka/, http://peer2:9002/eureka/,http://peer3:9003/eureka/
---
spring:
   profiles:
     active:  provider-payment02