server:
  port: 8900

spring:
  application:
    name: spring-cloud-hystrix-provider
  profiles: peer1
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://localhost:9004/eureka/
---
server:
  port: 9001

spring:
  application:
    name: spring-cloud-hystrix-provider
  profiles: peer2
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler: #介于0到1之间,1表示全部采样
      probability: 1
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://localhost:9004/eureka/
---
spring:
  profiles:
    active: peer2